# Python: More Data Annotation and Numpy

Name: Collin Real

abc123: yhi267

Blank notebook to be used for class exercises.

## Exercise 1

Given the provided numpy array, write code that prints the following:
    
- Print the third row of the array
- Print the second column of the array
- Print the fourth row's third column (this should print a single number).

In [2]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [3]:
# Write Code Here
for g in grades[:3]:
    print(g[:2])
    
m0_sum = 0
m1_sum = 0
f_sum = 0
for g in grades:
    m0_sum += g[0]
    m1_sum += g[1]
    f_sum += g[2]
    
ns = len(grades)

print(m0_sum/ns, m1_sum/ns, f_sum/ns)

[79 95]
[95 60]
[99 67]
84.1 74.5 80.1


In [4]:
print(grades[2,])

print(grades[:, 1])

print(grades[3,2])

[99 67 84]
[95 60 67 76 84 69 65 73 89 67]
97


## Exercise 2

Given the provided array in the Lab file, write code the prints the following:

- The average grade per test (column) (this should print an array with 3 items)
- The average grade per row, i.e., the average test grade per student
- Print the max grade per test
- Print the average across all students (rows) and tests (columns)

In [5]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [6]:
# Write Code Here
print(grades.mean(axis=0))

print(grades.mean(axis=1))

print(grades.max(axis=0))

print(grades.mean())

[84.1 74.5 80.1]
[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
[99 95 98]
79.56666666666666


## Exercise 3

Write code that prints the grades of all students that have an average grade less than 90.

In [7]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [8]:
# Write Code Here
avg = grades.mean(axis=1)
print(avg)

bool_index = avg < 90

print(bool_index)

print(grades[bool_index,:])

[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
[ True  True  True  True False  True  True  True  True  True]
[[79 95 60]
 [95 60 61]
 [99 67 84]
 [76 76 97]
 [70 69 96]
 [88 65 76]
 [67 73 80]
 [82 89 61]
 [94 67 88]]


## Exercise 4

Write code to adds 10 points every student's test grade **if** their average test grade is greater than 90.

In [9]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [10]:
# Write Code Here
new_grades = grades.copy()

index_bool = grades.mean(axis=1)> 90

print(index_bool)

new_grades [index_bool] +=10

new_grades

[False False False False  True False False False False False]


array([[ 79,  95,  60],
       [ 95,  60,  61],
       [ 99,  67,  84],
       [ 76,  76,  97],
       [101,  94, 108],
       [ 70,  69,  96],
       [ 88,  65,  76],
       [ 67,  73,  80],
       [ 82,  89,  61],
       [ 94,  67,  88]])

## Exercise 5

Write a function that takes two 1-dimensional arrays as input and returns the euclidean distance between the two arrays.

Euclidean distance is defined as

$EDist = \sqrt{(x_0 - v_0)^2 + (x_1 - v_1)^2 + \dots + (x_{D-1} - v_{D-1})^2}$

The square root of a number in numpy can be calculated as np.sqrt(x), where x is a number or array.

Try to complete this exercise with for loops and with vector notation.

In [11]:
# Write Code Here
def edist1(x,y):
    score = 0 
    for i, j in zip(x,y):
        score += (i-j)**2
        
    return score ** 0.5
    
def edist2(x,y):
    return np.sqrt(((x-y)**2).sum())
        
x = np.array([1,2,3,4])

y = np.array([5,6,7,8])

print(edist1(x,y),edist2(x,y))

8.0 8.0


## Exercise 6

Write code to load the data in the "iris.csv" into numpy arrays.

The frst 4 columns are the features/attributes. The last column is the
class. Simply load the class as a list of strings. Don't forget to convert the
dataset into a numpy array. You can use either DictVectorizer or the CSV
method on the previous slide to load the features.

In [13]:
with open('iris (1).csv') as in_file:
    count = 0
    for row in in_file:
        print(row.strip())
        count += 1
        if count == 10:
            break

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa


In [15]:
# Write code here
# Write code here
import numpy as np
import csv

X = []
y = []

my_file = open('iris (1).csv')

iCSV = csv.reader(my_file, delimiter=',')

for row in iCSV:
    X.append([float(x) for x in row[:-1]])
    y.append(row[-1])

my_file.close()

X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [20]:
from sklearn.feature_extraction import DictVectorizer

X_list_dict = []
y = []

my_file = open('iris (1).csv')

iCSV = csv.reader(my_file, delimiter=',')

for row in iCSV:
    features = {'col_1': float(row[0]),
                'col_2': float(row[1]),
                'col_3': float(row[2]),
                'col_4': float(row[3])}
    X_list_dict.append(features)
    y.append(row[-1])

my_file.close()

vec = DictVectorizer(sparse=False)

X = vec.fit_transform(X_list_dict)
y = np.array(y)

print(X.shape)
print(y.shape)

vec.feature_names_

(150, 4)
(150,)


['col_1', 'col_2', 'col_3', 'col_4']